// Code generated by ../../gen/docs_json. DO NOT EDIT.

package BuildableStorage

import (
	"fmt"

	"github.com/l-ross/ficsit-toolkit/resource"
)

type FGBuildableStorage struct {
	Name                                 string
	ClassName                            string
	MAddToSignificanceManager            bool
	MAllowColoring                       bool
	MAttachmentPoints                    string
	MBuildEffectSpeed                    float64
	MCachedSkeletalMeshes                string
	MCanChangePotential                  bool
	MCreateClearanceMeshRepresentation   bool
	MDescription                         string
	MDisplayName                         string
	MDoesHaveShutdownAnimation           bool
	MEffectUpdateInterval                float64
	MFluidStackSizeDefault               resource.StackSize
	MFluidStackSizeMultiplier            int
	MForceNetUpdateOnRegisterPlayer      bool
	MHideOnBuildEffectStart              bool
	MHighlightVector                     string
	MInteractingPlayers                  string
	MInventorySizeX                      int
	MInventorySizeY                      int
	MIsUseable                           bool
	MMaxPotential                        float64
	MMaxPotentialIncreasePerCrystal      float64
	MMinPotential                        float64
	MMinimumProducingTime                float64
	MMinimumStoppedTime                  float64
	MNumCyclesForProductivity            int
	MOnHasPowerChanged                   string
	MOnHasProductionChanged              string
	MOnHasStandbyChanged                 string
	MPowerConsumption                    float64
	MPowerConsumptionExponent            float64
	MShouldModifyWorldGrid               bool
	MShouldShowAttachmentPointVisuals    bool
	MShouldShowHighlight                 bool
	MSignificanceRange                   float64
	MSkipBuildEffect                     bool
	MStackingHeight                      float64
	MToggleDormancyOnInteraction         bool
	MaxRenderDistance                    float64
	OnReplicationDetailActorCreatedEvent string
}

var (
	StorageContainerMk1 = FGBuildableStorage{
		Name:                               "StorageContainerMk1",
		ClassName:                          "Build_StorageContainerMk1_C",
		MAddToSignificanceManager:          false,
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCachedSkeletalMeshes:              ``,
		MCanChangePotential:                false,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Contains 24 slots for storing large amounts of items.
Has an input and output for conveyor belts.`,
		MDisplayName:                         `Storage Container`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            1,
		MForceNetUpdateOnRegisterPlayer:      true,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                  ``,
		MInventorySizeX:                      6,
		MInventorySizeY:                      4,
		MIsUseable:                           true,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MPowerConsumption:                    0.000000,
		MPowerConsumptionExponent:            1.600000,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    false,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MStackingHeight:                      400.000000,
		MToggleDormancyOnInteraction:         true,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}

	StorageContainerMk2 = FGBuildableStorage{
		Name:                               "StorageContainerMk2",
		ClassName:                          "Build_StorageContainerMk2_C",
		MAddToSignificanceManager:          false,
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCachedSkeletalMeshes:              ``,
		MCanChangePotential:                false,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Contains 48 slots for storing large amounts of items.
Has two inputs and outputs for conveyor belts.`,
		MDisplayName:                         `Industrial Storage Container`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            1,
		MForceNetUpdateOnRegisterPlayer:      true,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                  ``,
		MInventorySizeX:                      8,
		MInventorySizeY:                      6,
		MIsUseable:                           true,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MPowerConsumption:                    0.000000,
		MPowerConsumptionExponent:            1.600000,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    false,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MStackingHeight:                      800.000000,
		MToggleDormancyOnInteraction:         true,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}

	StorageHazard = FGBuildableStorage{
		Name:                                 "StorageHazard",
		ClassName:                            "Build_StorageHazard_C",
		MAddToSignificanceManager:            false,
		MAllowColoring:                       true,
		MAttachmentPoints:                    ``,
		MBuildEffectSpeed:                    0.000000,
		MCachedSkeletalMeshes:                ``,
		MCanChangePotential:                  false,
		MCreateClearanceMeshRepresentation:   true,
		MDescription:                         `Contains 25 slots for storing large amounts of items.`,
		MDisplayName:                         `Hazard Storage Box`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            1,
		MForceNetUpdateOnRegisterPlayer:      true,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                  ``,
		MInventorySizeX:                      5,
		MInventorySizeY:                      5,
		MIsUseable:                           true,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MPowerConsumption:                    0.000000,
		MPowerConsumptionExponent:            1.600000,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    false,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MStackingHeight:                      0.000000,
		MToggleDormancyOnInteraction:         true,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}

	StorageMedkit = FGBuildableStorage{
		Name:                                 "StorageMedkit",
		ClassName:                            "Build_StorageMedkit_C",
		MAddToSignificanceManager:            false,
		MAllowColoring:                       true,
		MAttachmentPoints:                    ``,
		MBuildEffectSpeed:                    0.000000,
		MCachedSkeletalMeshes:                ``,
		MCanChangePotential:                  false,
		MCreateClearanceMeshRepresentation:   true,
		MDescription:                         `Contains 25 slots for storing large amounts of items.`,
		MDisplayName:                         `Medical Storage Box`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            1,
		MForceNetUpdateOnRegisterPlayer:      true,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                  ``,
		MInventorySizeX:                      5,
		MInventorySizeY:                      5,
		MIsUseable:                           true,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MPowerConsumption:                    0.000000,
		MPowerConsumptionExponent:            1.600000,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    false,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MStackingHeight:                      0.000000,
		MToggleDormancyOnInteraction:         true,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}

	StoragePlayer = FGBuildableStorage{
		Name:                                 "StoragePlayer",
		ClassName:                            "Build_StoragePlayer_C",
		MAddToSignificanceManager:            false,
		MAllowColoring:                       true,
		MAttachmentPoints:                    ``,
		MBuildEffectSpeed:                    0.000000,
		MCachedSkeletalMeshes:                ``,
		MCanChangePotential:                  false,
		MCreateClearanceMeshRepresentation:   true,
		MDescription:                         `Contains 25 slots for storing large amounts of items.`,
		MDisplayName:                         `Personal Storage Box`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            1,
		MForceNetUpdateOnRegisterPlayer:      true,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                  ``,
		MInventorySizeX:                      5,
		MInventorySizeY:                      5,
		MIsUseable:                           true,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MPowerConsumption:                    0.000000,
		MPowerConsumptionExponent:            1.600000,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    false,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MStackingHeight:                      0.000000,
		MToggleDormancyOnInteraction:         true,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}
)

func GetByClassName(className string) (FGBuildableStorage, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGBuildableStorage{}, fmt.Errorf("failed to find FGBuildableStorage with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGBuildableStorage{
	"Build_StorageContainerMk1_C": StorageContainerMk1,
	"Build_StorageContainerMk2_C": StorageContainerMk2,
	"Build_StorageHazard_C":       StorageHazard,
	"Build_StorageMedkit_C":       StorageMedkit,
	"Build_StoragePlayer_C":       StoragePlayer,
}
