// Code generated by ../../gen/docs_json. DO NOT EDIT.

package BuildableTrainPlatformCargo

import (
	"fmt"

	"github.com/l-ross/ficsit-toolkit/resource"
)

type FGBuildableTrainPlatformCargo struct {
	Name                                 string
	ClassName                            string
	MAddToSignificanceManager            bool
	MAllowColoring                       bool
	MAttachmentPoints                    string
	MBuildEffectSpeed                    float64
	MCachedSkeletalMeshes                string
	MCanChangePotential                  bool
	MCanLoadAny                          bool
	MCanUnloadAny                        bool
	MCreateClearanceMeshRepresentation   bool
	MCurrentDockForDuration              float64
	MDescription                         string
	MDisplayName                         string
	MDockForDuration                     float64
	MDockWasCancelled                    bool
	MDockingRuleSet                      string
	MDockingSequenceTimerHandle          string
	MDoesHaveShutdownAnimation           bool
	MEffectUpdateInterval                float64
	MFluidStackSizeDefault               resource.StackSize
	MFluidStackSizeMultiplier            int
	MForceNetUpdateOnRegisterPlayer      bool
	MFreightCargoType                    string
	MHasFullyLoadUnloadRule              bool
	MHideOnBuildEffectStart              bool
	MHighlightVector                     string
	MIdleUpdateTimerHandle               string
	MInteractingPlayers                  string
	MIsFullLoad                          bool
	MIsFullUnload                        bool
	MIsOrientationReversed               bool
	MIsUseable                           bool
	MLoadItemFilter                      string
	MMaxPotential                        float64
	MMaxPotentialIncreasePerCrystal      float64
	MMinPotential                        float64
	MMinimumProducingTime                float64
	MMinimumStoppedTime                  float64
	MMustDockForDuration                 bool
	MNumCyclesForProductivity            int
	MOnHasPowerChanged                   string
	MOnHasProductionChanged              string
	MOnHasStandbyChanged                 string
	MOnTransferRateUpdated               string
	MPipeInputConnections                string
	MPipeOutputConnections               string
	MPlatformConnections                 string
	MPlatformDockingStatus               string
	MPotentialDockers                    string
	MPowerConsumption                    float64
	MPowerConsumptionExponent            float64
	MRanCompleteBeforeNone               bool
	MReplicatedInflowRate                float64
	MReplicatedOutflowRate               float64
	MSavedDockingStatus                  string
	MShouldExecuteLoadOrUnload           bool
	MShouldModifyWorldGrid               bool
	MShouldShowAttachmentPointVisuals    bool
	MShouldShowHighlight                 bool
	MSignificanceRange                   float64
	MSkipBuildEffect                     bool
	MSmoothedLoadRate                    float64
	MSmoothedUnloadRate                  float64
	MStorageInputConnections             string
	MStorageSizeX                        int
	MStorageSizeY                        int
	MSwapCargoVisibilityTimerHandle      string
	MTimeSinceLastLoadTransferUpdate     float64
	MTimeSinceLastUnloadTransferUpdate   float64
	MTimeToCompleteLoad                  float64
	MTimeToCompleteUnload                float64
	MTimeToSwapLoadVisibility            float64
	MTimeToSwapUnloadVisibility          float64
	MToggleDormancyOnInteraction         bool
	MUnloadItemFilter                    string
	MWaitForConditionUpdatePeriod        float64
	MaxRenderDistance                    float64
	OnReplicationDetailActorCreatedEvent string
}

var (
	TrainDockingStation = FGBuildableTrainPlatformCargo{
		Name:                               "TrainDockingStation",
		ClassName:                          "Build_TrainDockingStation_C",
		MAddToSignificanceManager:          true,
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCachedSkeletalMeshes:              ``,
		MCanChangePotential:                false,
		MCanLoadAny:                        false,
		MCanUnloadAny:                      false,
		MCreateClearanceMeshRepresentation: true,
		MCurrentDockForDuration:            0.000000,
		MDescription: `Freight Cars that stop at the Freight Platform will be loaded or unloaded by the Freight Platform.
Loading and unloading options can be set inside the building.
Snaps to other Platforms and Stations.
Needs to be connected to a powered Railway to function.`,
		MDisplayName:                         `Freight Platform`,
		MDockForDuration:                     0.000000,
		MDockWasCancelled:                    false,
		MDockingRuleSet:                      `(DockForDuration=15.000000)`,
		MDockingSequenceTimerHandle:          `()`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            1,
		MForceNetUpdateOnRegisterPlayer:      false,
		MFreightCargoType:                    `FCT_Standard`,
		MHasFullyLoadUnloadRule:              false,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MIdleUpdateTimerHandle:               `()`,
		MInteractingPlayers:                  ``,
		MIsFullLoad:                          false,
		MIsFullUnload:                        false,
		MIsOrientationReversed:               false,
		MIsUseable:                           true,
		MLoadItemFilter:                      ``,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MMustDockForDuration:                 false,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MOnTransferRateUpdated:               `()`,
		MPipeInputConnections:                ``,
		MPipeOutputConnections:               ``,
		MPlatformConnections:                 `(FGTrainPlatformConnection'"/Game/FactoryGame/Buildable/Factory/Train/Station/Build_TrainDockingStation.Default__Build_TrainDockingStation_C:PlatformConnection0"',FGTrainPlatformConnection'"/Game/FactoryGame/Buildable/Factory/Train/Station/Build_TrainDockingStation.Default__Build_TrainDockingStation_C:PlatformConnection1"')`,
		MPlatformDockingStatus:               `ETPDS_None`,
		MPotentialDockers:                    ``,
		MPowerConsumption:                    50.000000,
		MPowerConsumptionExponent:            1.600000,
		MRanCompleteBeforeNone:               false,
		MReplicatedInflowRate:                0.000000,
		MReplicatedOutflowRate:               0.000000,
		MSavedDockingStatus:                  `ETPDS_None`,
		MShouldExecuteLoadOrUnload:           false,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    true,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MSmoothedLoadRate:                    0.000000,
		MSmoothedUnloadRate:                  0.000000,
		MStorageInputConnections:             ``,
		MStorageSizeX:                        8,
		MStorageSizeY:                        6,
		MSwapCargoVisibilityTimerHandle:      `()`,
		MTimeSinceLastLoadTransferUpdate:     0.000000,
		MTimeSinceLastUnloadTransferUpdate:   0.000000,
		MTimeToCompleteLoad:                  27.000000,
		MTimeToCompleteUnload:                27.000000,
		MTimeToSwapLoadVisibility:            20.000000,
		MTimeToSwapUnloadVisibility:          6.000000,
		MToggleDormancyOnInteraction:         false,
		MUnloadItemFilter:                    ``,
		MWaitForConditionUpdatePeriod:        2.500000,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}

	TrainDockingStationLiquid = FGBuildableTrainPlatformCargo{
		Name:                               "TrainDockingStationLiquid",
		ClassName:                          "Build_TrainDockingStationLiquid_C",
		MAddToSignificanceManager:          true,
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCachedSkeletalMeshes:              ``,
		MCanChangePotential:                false,
		MCanLoadAny:                        false,
		MCanUnloadAny:                      false,
		MCreateClearanceMeshRepresentation: true,
		MCurrentDockForDuration:            0.000000,
		MDescription: `Freight Cars that stop at the Freight Platform will be loaded or unloaded by the Freight Platform.
Loading and unloading options can be set inside the building.
Snaps to other Platforms and Stations.
Needs to be connected to a powered Railway to function.`,
		MDisplayName:                         `Fluid Freight Platform`,
		MDockForDuration:                     0.000000,
		MDockWasCancelled:                    false,
		MDockingRuleSet:                      `(DockForDuration=15.000000)`,
		MDockingSequenceTimerHandle:          `()`,
		MDoesHaveShutdownAnimation:           false,
		MEffectUpdateInterval:                0.000000,
		MFluidStackSizeDefault:               resource.Fluid,
		MFluidStackSizeMultiplier:            48,
		MForceNetUpdateOnRegisterPlayer:      false,
		MFreightCargoType:                    `FCT_Liquid`,
		MHasFullyLoadUnloadRule:              false,
		MHideOnBuildEffectStart:              false,
		MHighlightVector:                     `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MIdleUpdateTimerHandle:               `()`,
		MInteractingPlayers:                  ``,
		MIsFullLoad:                          false,
		MIsFullUnload:                        false,
		MIsOrientationReversed:               false,
		MIsUseable:                           true,
		MLoadItemFilter:                      ``,
		MMaxPotential:                        1.000000,
		MMaxPotentialIncreasePerCrystal:      0.500000,
		MMinPotential:                        0.010000,
		MMinimumProducingTime:                2.000000,
		MMinimumStoppedTime:                  5.000000,
		MMustDockForDuration:                 false,
		MNumCyclesForProductivity:            20,
		MOnHasPowerChanged:                   `()`,
		MOnHasProductionChanged:              `()`,
		MOnHasStandbyChanged:                 `()`,
		MOnTransferRateUpdated:               `()`,
		MPipeInputConnections:                ``,
		MPipeOutputConnections:               ``,
		MPlatformConnections:                 `(FGTrainPlatformConnection'"/Game/FactoryGame/Buildable/Factory/Train/Station/Build_TrainDockingStationLiquid.Default__Build_TrainDockingStationLiquid_C:PlatformConnection0"',FGTrainPlatformConnection'"/Game/FactoryGame/Buildable/Factory/Train/Station/Build_TrainDockingStationLiquid.Default__Build_TrainDockingStationLiquid_C:PlatformConnection1"')`,
		MPlatformDockingStatus:               `ETPDS_None`,
		MPotentialDockers:                    ``,
		MPowerConsumption:                    50.000000,
		MPowerConsumptionExponent:            1.600000,
		MRanCompleteBeforeNone:               false,
		MReplicatedInflowRate:                0.000000,
		MReplicatedOutflowRate:               0.000000,
		MSavedDockingStatus:                  `ETPDS_None`,
		MShouldExecuteLoadOrUnload:           false,
		MShouldModifyWorldGrid:               true,
		MShouldShowAttachmentPointVisuals:    true,
		MShouldShowHighlight:                 false,
		MSignificanceRange:                   18000.000000,
		MSkipBuildEffect:                     false,
		MSmoothedLoadRate:                    0.000000,
		MSmoothedUnloadRate:                  0.000000,
		MStorageInputConnections:             ``,
		MStorageSizeX:                        1,
		MStorageSizeY:                        1,
		MSwapCargoVisibilityTimerHandle:      `()`,
		MTimeSinceLastLoadTransferUpdate:     0.000000,
		MTimeSinceLastUnloadTransferUpdate:   0.000000,
		MTimeToCompleteLoad:                  27.000000,
		MTimeToCompleteUnload:                27.000000,
		MTimeToSwapLoadVisibility:            20.000000,
		MTimeToSwapUnloadVisibility:          6.000000,
		MToggleDormancyOnInteraction:         false,
		MUnloadItemFilter:                    ``,
		MWaitForConditionUpdatePeriod:        2.500000,
		MaxRenderDistance:                    -1.000000,
		OnReplicationDetailActorCreatedEvent: `()`,
	}
)

func GetByClassName(className string) (FGBuildableTrainPlatformCargo, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGBuildableTrainPlatformCargo{}, fmt.Errorf("failed to find FGBuildableTrainPlatformCargo with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGBuildableTrainPlatformCargo{
	"Build_TrainDockingStation_C":       TrainDockingStation,
	"Build_TrainDockingStationLiquid_C": TrainDockingStationLiquid,
}
