// Code generated by ../../gen/docs_json. DO NOT EDIT.

package BuildablePillar

import (
	"fmt"
)

type FGBuildablePillar struct {
	Name                               string
	ClassName                          string
	MAllowColoring                     bool
	MAttachmentPoints                  string
	MBuildEffectSpeed                  float64
	MCreateClearanceMeshRepresentation bool
	MDescription                       string
	MDisplayName                       string
	MForceNetUpdateOnRegisterPlayer    bool
	MHideOnBuildEffectStart            bool
	MHighlightVector                   string
	MInteractingPlayers                string
	MIsSupport                         bool
	MIsUseable                         bool
	MShouldModifyWorldGrid             bool
	MShouldShowAttachmentPointVisuals  bool
	MShouldShowHighlight               bool
	MSize                              string
	MSkipBuildEffect                   bool
	MToggleDormancyOnInteraction       bool
	MaxRenderDistance                  float64
}

var (
	PillarBase = FGBuildablePillar{
		Name:                               "PillarBase",
		ClassName:                          "Build_PillarBase_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription:                       `The Pillar Support snaps to Pillars and can be placed on, for example, Foundations and Walls.`,
		MDisplayName:                       `Big Pillar Support`,
		MForceNetUpdateOnRegisterPlayer:    false,
		MHideOnBuildEffectStart:            false,
		MHighlightVector:                   `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                ``,
		MIsSupport:                         true,
		MIsUseable:                         false,
		MShouldModifyWorldGrid:             true,
		MShouldShowAttachmentPointVisuals:  false,
		MShouldShowHighlight:               false,
		MSize:                              `(X=800.000000,Y=800.000000,Z=400.000000)`,
		MSkipBuildEffect:                   false,
		MToggleDormancyOnInteraction:       false,
		MaxRenderDistance:                  -1.000000,
	}

	PillarBaseSmall = FGBuildablePillar{
		Name:                               "PillarBaseSmall",
		ClassName:                          "Build_PillarBase_Small_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription:                       `The Pillar Support snaps to Pillars and can be placed on, for example, Foundations and Walls.`,
		MDisplayName:                       `Small Pillar Support`,
		MForceNetUpdateOnRegisterPlayer:    false,
		MHideOnBuildEffectStart:            false,
		MHighlightVector:                   `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                ``,
		MIsSupport:                         true,
		MIsUseable:                         false,
		MShouldModifyWorldGrid:             true,
		MShouldShowAttachmentPointVisuals:  false,
		MShouldShowHighlight:               false,
		MSize:                              `(X=400.000000,Y=400.000000,Z=200.000000)`,
		MSkipBuildEffect:                   false,
		MToggleDormancyOnInteraction:       false,
		MaxRenderDistance:                  -1.000000,
	}

	PillarMiddle = FGBuildablePillar{
		Name:                               "PillarMiddle",
		ClassName:                          "Build_PillarMiddle_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to other Pillars and can be placed on, for example, Foundations and Walls.

Size: 4m x 4m`,
		MDisplayName:                      `Big Metal Pillar`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsSupport:                        false,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             `(X=400.000000,Y=400.000000,Z=400.000000)`,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	PillarMiddleConcrete = FGBuildablePillar{
		Name:                               "PillarMiddleConcrete",
		ClassName:                          "Build_PillarMiddle_Concrete_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to other Pillars and can be placed on, for example, Foundations and Walls.

Size: 4m x 4m`,
		MDisplayName:                      `Big Concrete Pillar`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsSupport:                        false,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             `(X=400.000000,Y=400.000000,Z=400.000000)`,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	PillarMiddleFrame = FGBuildablePillar{
		Name:                               "PillarMiddleFrame",
		ClassName:                          "Build_PillarMiddle_Frame_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to other Pillars and can be placed on, for example, Foundations and Walls.

Size: 4m x 4m`,
		MDisplayName:                      `Big Frame Pillar`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsSupport:                        false,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             `(X=400.000000,Y=400.000000,Z=400.000000)`,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	PillarSmallConcrete = FGBuildablePillar{
		Name:                               "PillarSmallConcrete",
		ClassName:                          "Build_Pillar_Small_Concrete_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to other Pillars and can be placed on, for example, Foundations and Walls.

Size: 2m x 4m`,
		MDisplayName:                      `Small Concrete Pillar`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsSupport:                        false,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             `(X=200.000000,Y=200.000000,Z=400.000000)`,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	PillarSmallFrame = FGBuildablePillar{
		Name:                               "PillarSmallFrame",
		ClassName:                          "Build_Pillar_Small_Frame_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to other Pillars and can be placed on, for example, Foundations and Walls.

Size: 2m x 4m`,
		MDisplayName:                      `Small Frame Pillar`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsSupport:                        false,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             `(X=200.000000,Y=200.000000,Z=400.000000)`,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	PillarSmallMetal = FGBuildablePillar{
		Name:                               "PillarSmallMetal",
		ClassName:                          "Build_Pillar_Small_Metal_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to other Pillars and can be placed on, for example, Foundations and Walls.

Size: 2m x 4m`,
		MDisplayName:                      `Small Metal Pillar`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsSupport:                        false,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             `(X=200.000000,Y=200.000000,Z=400.000000)`,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	PillarTop = FGBuildablePillar{
		Name:                               "PillarTop",
		ClassName:                          "Build_PillarTop_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription:                       `Pillar Top`,
		MDisplayName:                       `Pillar Top`,
		MForceNetUpdateOnRegisterPlayer:    false,
		MHideOnBuildEffectStart:            false,
		MHighlightVector:                   `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                ``,
		MIsSupport:                         false,
		MIsUseable:                         false,
		MShouldModifyWorldGrid:             true,
		MShouldShowAttachmentPointVisuals:  false,
		MShouldShowHighlight:               false,
		MSize:                              `(X=800.000000,Y=800.000000,Z=400.000000)`,
		MSkipBuildEffect:                   false,
		MToggleDormancyOnInteraction:       false,
		MaxRenderDistance:                  -1.000000,
	}
)

func GetByClassName(className string) (FGBuildablePillar, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGBuildablePillar{}, fmt.Errorf("failed to find FGBuildablePillar with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGBuildablePillar{
	"Build_PillarBase_C":            PillarBase,
	"Build_PillarBase_Small_C":      PillarBaseSmall,
	"Build_PillarMiddle_C":          PillarMiddle,
	"Build_PillarMiddle_Concrete_C": PillarMiddleConcrete,
	"Build_PillarMiddle_Frame_C":    PillarMiddleFrame,
	"Build_Pillar_Small_Concrete_C": PillarSmallConcrete,
	"Build_Pillar_Small_Frame_C":    PillarSmallFrame,
	"Build_Pillar_Small_Metal_C":    PillarSmallMetal,
	"Build_PillarTop_C":             PillarTop,
}
