// Code generated by ../../gen/docs_json. DO NOT EDIT.

package ConveyorPoleStackable

import (
	"fmt"
)

type FGConveyorPoleStackable struct {
	Name                               string
	ClassName                          string
	MAllowColoring                     bool
	MAttachmentPoints                  string
	MBuildEffectSpeed                  float64
	MCanStack                          bool
	MCreateClearanceMeshRepresentation bool
	MDescription                       string
	MDisplayName                       string
	MForceNetUpdateOnRegisterPlayer    bool
	MHeight                            float64
	MHideOnBuildEffectStart            bool
	MHighlightVector                   string
	MInteractingPlayers                string
	MIsUseable                         bool
	MShouldModifyWorldGrid             bool
	MShouldShowAttachmentPointVisuals  bool
	MShouldShowHighlight               bool
	MSkipBuildEffect                   bool
	MStackHeight                       float64
	MToggleDormancyOnInteraction       bool
	MUseStaticHeight                   bool
	MaxRenderDistance                  float64
}

var (
	ConveyorPoleStackable = FGConveyorPoleStackable{
		Name:                               "ConveyorPoleStackable",
		ClassName:                          "Build_ConveyorPoleStackable_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCanStack:                          true,
		MCreateClearanceMeshRepresentation: false,
		MDescription:                       `Support for conveyor belts. Can be stacked on other stackable supports.`,
		MDisplayName:                       `Stackable Conveyor Pole`,
		MForceNetUpdateOnRegisterPlayer:    false,
		MHeight:                            100.000000,
		MHideOnBuildEffectStart:            false,
		MHighlightVector:                   `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:                ``,
		MIsUseable:                         false,
		MShouldModifyWorldGrid:             true,
		MShouldShowAttachmentPointVisuals:  false,
		MShouldShowHighlight:               false,
		MSkipBuildEffect:                   false,
		MStackHeight:                       200.000000,
		MToggleDormancyOnInteraction:       false,
		MUseStaticHeight:                   true,
		MaxRenderDistance:                  -1.000000,
	}
)

func GetByClassName(className string) (FGConveyorPoleStackable, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGConveyorPoleStackable{}, fmt.Errorf("failed to find FGConveyorPoleStackable with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGConveyorPoleStackable{
	"Build_ConveyorPoleStackable_C": ConveyorPoleStackable,
}
