// Code generated by ../../gen/docs_json. DO NOT EDIT.

package BuildableCornerWall

import (
	"fmt"
)

type FGBuildableCornerWall struct {
	Name                               string
	ClassName                          string
	MAllowColoring                     bool
	MAttachmentPoints                  string
	MBuildEffectSpeed                  float64
	MCreateClearanceMeshRepresentation bool
	MDescription                       string
	MDisplayName                       string
	MForceNetUpdateOnRegisterPlayer    bool
	MHeight                            float64
	MHideOnBuildEffectStart            bool
	MHighlightVector                   string
	MInteractingPlayers                string
	MIsUseable                         bool
	MShouldModifyWorldGrid             bool
	MShouldShowAttachmentPointVisuals  bool
	MShouldShowHighlight               bool
	MSize                              float64
	MSkipBuildEffect                   bool
	MToggleDormancyOnInteraction       bool
	MaxRenderDistance                  float64
}

var (
	WallConcrete8x4Corner01 = FGBuildableCornerWall{
		Name:                               "WallConcrete8x4Corner01",
		ClassName:                          "Build_Wall_Concrete_8x4_Corner_01_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to foundations and other walls.
Useful for building multi-floor structures.

Size: 8m x 4m`,
		MDisplayName:                      `Tilted Corner Wall 4m`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHeight:                           400.000000,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             800.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	WallConcrete8x8Corner01 = FGBuildableCornerWall{
		Name:                               "WallConcrete8x8Corner01",
		ClassName:                          "Build_Wall_Concrete_8x8_Corner_01_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to foundations and other walls.
Useful for building multi-floor structures.

Size: 8m x 8m`,
		MDisplayName:                      `Tilted Corner Wall 8m`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHeight:                           800.000000,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             800.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	WallOrange8x4Corner01 = FGBuildableCornerWall{
		Name:                               "WallOrange8x4Corner01",
		ClassName:                          "Build_Wall_Orange_8x4_Corner_01_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to foundations and other walls.
Useful for building multi-floor structures.

Size: 8m x 4m`,
		MDisplayName:                      `Tilted Corner Wall 4m`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHeight:                           400.000000,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             800.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	WallOrange8x8Corner01 = FGBuildableCornerWall{
		Name:                               "WallOrange8x8Corner01",
		ClassName:                          "Build_Wall_Orange_8x8_Corner_01_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to foundations and other walls.
Useful for building multi-floor structures.

Size: 8m x 8m`,
		MDisplayName:                      `Tilted Corner Wall 8m`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHeight:                           800.000000,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             800.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	WallSteel8x4Corner01 = FGBuildableCornerWall{
		Name:                               "WallSteel8x4Corner01",
		ClassName:                          "Build_Wall_Steel_8x4_Corner_01_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to foundations and other walls.
Useful for building multi-floor structures.

Size: 8m x 4m`,
		MDisplayName:                      `Tilted Corner Wall 4m`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHeight:                           400.000000,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             800.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}

	WallSteel8x8Corner01 = FGBuildableCornerWall{
		Name:                               "WallSteel8x8Corner01",
		ClassName:                          "Build_Wall_Steel_8x8_Corner_01_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MDescription: `Snaps to foundations and other walls.
Useful for building multi-floor structures.

Size: 8m x 8m`,
		MDisplayName:                      `Tilted Corner Wall 8m`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHeight:                           800.000000,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        false,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSize:                             800.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}
)

func GetByClassName(className string) (FGBuildableCornerWall, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGBuildableCornerWall{}, fmt.Errorf("failed to find FGBuildableCornerWall with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGBuildableCornerWall{
	"Build_Wall_Concrete_8x4_Corner_01_C": WallConcrete8x4Corner01,
	"Build_Wall_Concrete_8x8_Corner_01_C": WallConcrete8x8Corner01,
	"Build_Wall_Orange_8x4_Corner_01_C":   WallOrange8x4Corner01,
	"Build_Wall_Orange_8x8_Corner_01_C":   WallOrange8x8Corner01,
	"Build_Wall_Steel_8x4_Corner_01_C":    WallSteel8x4Corner01,
	"Build_Wall_Steel_8x8_Corner_01_C":    WallSteel8x8Corner01,
}
