// Code generated by ../../gen/docs_json. DO NOT EDIT.

package Weapon

import (
	"fmt"

	"github.com/l-ross/ficsit-toolkit/resource"
)

type FGWeapon struct {
	Name                             string
	ClassName                        string
	Fire                             string
	MAimTime                         float64
	MAllowedAmmoClasses              string
	MAmmoCycleMode                   string
	MAmmoSwitchUsedRadialMenu        bool
	MArmAnimation                    string
	MAttachSocket                    string
	MAutoReloadDelay                 float64
	MAutoReloadTimerHandle           string
	MAutomaticallyReload             bool
	MBackAnimation                   string
	MBaseAimTime                     float64
	MBaseFiringDispersion            float64
	MBaseRestingDispersion           float64
	MBlockSprintWhenFiring           bool
	MCostToUse                       string
	MCurrentAmmoCount                int
	MCurrentDispersion               float64
	MDispersionChangePerShot         float64
	MEquipmentSlot                   resource.EquipmentSlot
	MFireRate                        float64
	MFiringBlocksDispersionReduction bool
	MFiringDispersion                float64
	MHasPersistentOwner              bool
	MHasReloadedOnce                 bool
	MLockAngle                       float64
	MMuteDryFire                     bool
	MOldState                        string
	MOnAmmoCyclingPressed            string
	MOnAmmoCyclingReleased           string
	MOnWeaponStateChanged            string
	MRandomReloadAnim                int
	MRandomStingerAnim               int
	MReloadTime                      float64
	MRestingDispersion               float64
	MShowCycleAmmoRadialMenuTimer    string
	MUseDefaultPrimaryFire           bool
	MWeaponDamageMultiplier          float64
	MWeaponState                     string
}

var (
	RebarGunProjectile = FGWeapon{
		Name:                             "RebarGunProjectile",
		ClassName:                        "Equip_RebarGun_Projectile_C",
		MAimTime:                         1.000000,
		MAllowedAmmoClasses:              `(BlueprintGeneratedClass'"/Game/FactoryGame/Resource/Parts/SpikedRebar/Desc_SpikedRebar.Desc_SpikedRebar_C"')`,
		MAmmoCycleMode:                   `IE_Released`,
		MAmmoSwitchUsedRadialMenu:        false,
		MArmAnimation:                    `AE_RebarGun`,
		MAttachSocket:                    `hand_rSocket`,
		MAutoReloadDelay:                 0.500000,
		MAutoReloadTimerHandle:           `()`,
		MAutomaticallyReload:             false,
		MBackAnimation:                   `BE_None`,
		MBaseAimTime:                     0.000000,
		MBaseFiringDispersion:            0.000000,
		MBaseRestingDispersion:           0.000000,
		MBlockSprintWhenFiring:           true,
		MCostToUse:                       ``,
		MCurrentAmmoCount:                0,
		MCurrentDispersion:               0.000000,
		MDispersionChangePerShot:         0.000000,
		MEquipmentSlot:                   resource.Arms,
		MFireRate:                        1.000000,
		MFiringBlocksDispersionReduction: false,
		MFiringDispersion:                3.000000,
		MHasPersistentOwner:              false,
		MMuteDryFire:                     false,
		MOldState:                        `(EWS_Unequipped)`,
		MOnAmmoCyclingPressed:            `()`,
		MOnAmmoCyclingReleased:           `()`,
		MOnWeaponStateChanged:            `()`,
		MRandomReloadAnim:                0,
		MRandomStingerAnim:               0,
		MReloadTime:                      1.800000,
		MRestingDispersion:               0.200000,
		MShowCycleAmmoRadialMenuTimer:    `()`,
		MUseDefaultPrimaryFire:           false,
		MWeaponDamageMultiplier:          1.000000,
		MWeaponState:                     `EWS_Unequipped`,
	}

	Rifle = FGWeapon{
		Name:                             "Rifle",
		ClassName:                        "Equip_Rifle_C",
		Fire:                             `()`,
		MAimTime:                         1.000000,
		MAllowedAmmoClasses:              `(BlueprintGeneratedClass'"/Game/FactoryGame/Resource/Parts/CartridgeStandard/Desc_CartridgeStandard.Desc_CartridgeStandard_C"')`,
		MAmmoCycleMode:                   `IE_Released`,
		MAmmoSwitchUsedRadialMenu:        false,
		MArmAnimation:                    `AE_Rifle`,
		MAttachSocket:                    `hand_rSocket`,
		MAutoReloadDelay:                 0.500000,
		MAutoReloadTimerHandle:           `()`,
		MAutomaticallyReload:             false,
		MBackAnimation:                   `BE_None`,
		MBaseAimTime:                     0.000000,
		MBaseFiringDispersion:            0.000000,
		MBaseRestingDispersion:           0.000000,
		MBlockSprintWhenFiring:           true,
		MCostToUse:                       ``,
		MCurrentAmmoCount:                0,
		MCurrentDispersion:               0.000000,
		MDispersionChangePerShot:         0.000000,
		MEquipmentSlot:                   resource.Arms,
		MFireRate:                        0.200000,
		MFiringBlocksDispersionReduction: true,
		MFiringDispersion:                3.000000,
		MHasPersistentOwner:              false,
		MHasReloadedOnce:                 false,
		MLockAngle:                       0.000000,
		MOldState:                        `(EWS_Unequipped)`,
		MOnAmmoCyclingPressed:            `()`,
		MOnAmmoCyclingReleased:           `()`,
		MOnWeaponStateChanged:            `()`,
		MReloadTime:                      3.200000,
		MRestingDispersion:               0.200000,
		MShowCycleAmmoRadialMenuTimer:    `()`,
		MUseDefaultPrimaryFire:           false,
		MWeaponDamageMultiplier:          1.000000,
		MWeaponState:                     `EWS_Unequipped`,
	}
)

func GetByClassName(className string) (FGWeapon, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGWeapon{}, fmt.Errorf("failed to find FGWeapon with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGWeapon{
	"Equip_RebarGun_Projectile_C": RebarGunProjectile,
	"Equip_Rifle_C":               Rifle,
}
