// Code generated by ../../gen/docs_json. DO NOT EDIT.

package BuildableMAM

import (
	"fmt"
)

type FGBuildableMAM struct {
	Name                               string
	ClassName                          string
	MAllowColoring                     bool
	MAttachmentPoints                  string
	MBuildEffectSpeed                  float64
	MCreateClearanceMeshRepresentation bool
	MCurrentResearchState              string
	MDescription                       string
	MDisplayName                       string
	MForceNetUpdateOnRegisterPlayer    bool
	MHideOnBuildEffectStart            bool
	MHighlightVector                   string
	MInteractingPlayers                string
	MIsUseable                         bool
	MOccupiedText                      string
	MShouldModifyWorldGrid             bool
	MShouldShowAttachmentPointVisuals  bool
	MShouldShowHighlight               bool
	MSignificanceRange                 float64
	MSkipBuildEffect                   bool
	MToggleDormancyOnInteraction       bool
	MaxRenderDistance                  float64
}

var (
	Mam = FGBuildableMAM{
		Name:                               "Mam",
		ClassName:                          "Build_Mam_C",
		MAllowColoring:                     true,
		MAttachmentPoints:                  ``,
		MBuildEffectSpeed:                  0.000000,
		MCreateClearanceMeshRepresentation: true,
		MCurrentResearchState:              `ERS_NotResearching`,
		MDescription: `The Molecular Analysis Machine is used to analyse new and exotic materials found on alien planets.
R&D will assist Pioneers through the MAM to turn any valuable data into usable research options and new technologies.`,
		MDisplayName:                      `MAM`,
		MForceNetUpdateOnRegisterPlayer:   false,
		MHideOnBuildEffectStart:           false,
		MHighlightVector:                  `(X=0.000000,Y=0.000000,Z=0.000000)`,
		MInteractingPlayers:               ``,
		MIsUseable:                        true,
		MOccupiedText:                     `The Molecular Analysis Machine is occupied!`,
		MShouldModifyWorldGrid:            true,
		MShouldShowAttachmentPointVisuals: false,
		MShouldShowHighlight:              false,
		MSignificanceRange:                5000.000000,
		MSkipBuildEffect:                  false,
		MToggleDormancyOnInteraction:      false,
		MaxRenderDistance:                 -1.000000,
	}
)

func GetByClassName(className string) (FGBuildableMAM, error) {
	if v, ok := ClassNameToDescriptor[className]; ok {
		return v, nil
	}

	return FGBuildableMAM{}, fmt.Errorf("failed to find FGBuildableMAM with class name %s", className)
}

var ClassNameToDescriptor = map[string]FGBuildableMAM{
	"Build_Mam_C": Mam,
}
